# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import regpro_pb2 as regpro__pb2


class regFuncStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.newServer = channel.unary_unary(
                '/regFunc/newServer',
                request_serializer=regpro__pb2.Name.SerializeToString,
                response_deserializer=regpro__pb2.Number.FromString,
                )
        self.fetchServers = channel.unary_unary(
                '/regFunc/fetchServers',
                request_serializer=regpro__pb2.Name.SerializeToString,
                response_deserializer=regpro__pb2.Name.FromString,
                )


class regFuncServicer(object):
    """Missing associated documentation comment in .proto file."""

    def newServer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def fetchServers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_regFuncServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'newServer': grpc.unary_unary_rpc_method_handler(
                    servicer.newServer,
                    request_deserializer=regpro__pb2.Name.FromString,
                    response_serializer=regpro__pb2.Number.SerializeToString,
            ),
            'fetchServers': grpc.unary_unary_rpc_method_handler(
                    servicer.fetchServers,
                    request_deserializer=regpro__pb2.Name.FromString,
                    response_serializer=regpro__pb2.Name.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'regFunc', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class regFunc(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def newServer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/regFunc/newServer',
            regpro__pb2.Name.SerializeToString,
            regpro__pb2.Number.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def fetchServers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/regFunc/fetchServers',
            regpro__pb2.Name.SerializeToString,
            regpro__pb2.Name.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
