# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: regpro.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cregpro.proto\"\"\n\x04Name\x12\x11\n\x04\x63ode\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\x07\n\x05_code\"&\n\x06Number\x12\x12\n\x05value\x18\x01 \x01(\x05H\x00\x88\x01\x01\x42\x08\n\x06_value2H\n\x07regFunc\x12\x1d\n\tnewServer\x12\x05.Name\x1a\x07.Number\"\x00\x12\x1e\n\x0c\x66\x65tchServers\x12\x05.Name\x1a\x05.Name\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'regpro_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NAME._serialized_start=16
  _NAME._serialized_end=50
  _NUMBER._serialized_start=52
  _NUMBER._serialized_end=90
  _REGFUNC._serialized_start=92
  _REGFUNC._serialized_end=164
# @@protoc_insertion_point(module_scope)
