# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: serverpro.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fserverpro.proto\"$\n\x06String\x12\x11\n\x04\x63ode\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\x07\n\x05_code\"$\n\x04Ints\x12\x12\n\x05value\x18\x01 \x01(\x05H\x00\x88\x01\x01\x42\x08\n\x06_value2I\n\nserverFunc\x12\x1b\n\x07\x61\x64\x64User\x12\x07.String\x1a\x05.Ints\"\x00\x12\x1e\n\nremoveUser\x12\x07.String\x1a\x05.Ints\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'serverpro_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STRING._serialized_start=19
  _STRING._serialized_end=55
  _INTS._serialized_start=57
  _INTS._serialized_end=93
  _SERVERFUNC._serialized_start=95
  _SERVERFUNC._serialized_end=168
# @@protoc_insertion_point(module_scope)
