# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: serverpro.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fserverpro.proto\"$\n\x06String\x12\x11\n\x04\x63ode\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\x07\n\x05_code\"$\n\x04Ints\x12\x12\n\x05value\x18\x01 \x01(\x05H\x00\x88\x01\x01\x42\x08\n\x06_value\"\xc7\x01\n\npubArticle\x12\x10\n\x06SPORTS\x18\x01 \x01(\x05H\x00\x12\x11\n\x07\x46\x41SHION\x18\x02 \x01(\x05H\x00\x12\x12\n\x08POLITICS\x18\x03 \x01(\x05H\x00\x12\x13\n\x06\x41uthor\x18\x04 \x01(\tH\x01\x88\x01\x01\x12\x11\n\x04Time\x18\x05 \x01(\x05H\x02\x88\x01\x01\x12\x14\n\x07\x43ontent\x18\x06 \x01(\tH\x03\x88\x01\x01\x12\x11\n\x04User\x18\x07 \x01(\tH\x04\x88\x01\x01\x42\x06\n\x04TypeB\t\n\x07_AuthorB\x07\n\x05_TimeB\n\n\x08_ContentB\x07\n\x05_User\"\xc5\x01\n\ngetArticle\x12\x10\n\x06SPORTS\x18\x01 \x01(\x05H\x00\x12\x11\n\x07\x46\x41SHION\x18\x02 \x01(\x05H\x00\x12\x12\n\x08POLITICS\x18\x03 \x01(\x05H\x00\x12\x13\n\x06\x41uthor\x18\x04 \x01(\tH\x01\x88\x01\x01\x12\x11\n\x04Time\x18\x05 \x01(\x05H\x02\x88\x01\x01\x12\x13\n\x06Timebf\x18\x06 \x01(\x05H\x03\x88\x01\x01\x12\x11\n\x04User\x18\x07 \x01(\tH\x04\x88\x01\x01\x42\x06\n\x04TypeB\t\n\x07_AuthorB\x07\n\x05_TimeB\t\n\x07_TimebfB\x07\n\x05_User2\x95\x01\n\nserverFunc\x12\x1b\n\x07\x61\x64\x64User\x12\x07.String\x1a\x05.Ints\"\x00\x12\x1e\n\nremoveUser\x12\x07.String\x1a\x05.Ints\"\x00\x12\"\n\naddArticle\x12\x0b.pubArticle\x1a\x05.Ints\"\x00\x12&\n\x0c\x66\x65tchArticle\x12\x0b.getArticle\x1a\x07.String\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'serverpro_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STRING._serialized_start=19
  _STRING._serialized_end=55
  _INTS._serialized_start=57
  _INTS._serialized_end=93
  _PUBARTICLE._serialized_start=96
  _PUBARTICLE._serialized_end=295
  _GETARTICLE._serialized_start=298
  _GETARTICLE._serialized_end=495
  _SERVERFUNC._serialized_start=498
  _SERVERFUNC._serialized_end=647
# @@protoc_insertion_point(module_scope)
